#!/bin/sh

VELUX_NIBE_CONFIG="${SYNOPKG_PKGDEST}/velux-nibe.conf"
cat > "${VELUX_NIBE_CONFIG}" <<EOF
{
  "velux_user": "${VELUX_USERNAME}",
  "velux_password": "${VELUX_PASSWORD}",
  "nibe_client_id": "${NIBE_CLIENT_ID}",
  "nibe_client_secret": "${NIBE_CLIENT_SECRET}",
  "nibe_callback": "${NIBE_CALLBACK_URL}",
  "nibe_system": ${NIBE_SYSTEM_ID},
  "interval": ${POLL_INTERVAL},
  "target_temperature": ${TARGET_TEMP},
  "http_port": ${HTTP_PORT}
}
EOF

exit 0
