#!/bin/bash
case "$1" in
start)
  if [ "${EUID}" -eq 0 ]; then
    sudo -u veluxnibe synosystemctl start pkguser-velux-nibe
  else
    synosystemctl start pkguser-velux-nibe
  fi
  ;;
stop)
  if [ "${EUID}" -eq 0 ]; then
    sudo -u veluxnibe synosystemctl stop pkguser-velux-nibe
  else
    synosystemctl stop pkguser-velux-nibe
  fi
  ;;
status)
  if [ "${EUID}" -eq 0 ]; then
    sudo -u veluxnibe synosystemctl get-active-status pkguser-velux-nibe
  else
    synosystemctl get-active-status pkguser-velux-nibe
  fi
  ;;
log)
  exec tail -n 100 -f "/var/packages/velux-nibe/target/velux-nibe.log"
  ;;
*)
  echo "Usage: $0 {start|stop|status}" >&2
  exit 1
  ;;
esac
